config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/intro/edit', to: 'users/registrations#edit_intro', as: 'edit_user_intro'
    post 'users/intro/edit', to: 'users/registrations#update_intro', as: 'update_user_intro'
  end

  resources :user, only: [] do
    member do
      post :follow
    end
  end

  resources :stories do
    member do
      post :unpublish
      post :publish
      post :love
    end
    resources :comments, only: [:create]
  end

  get '@:username/:story_id', to: 'pages#show', as: 'story_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  
  resources :pending_stories


  root 'pages#index'


 

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-primary">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>
    </div>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= avatar(current_user, size: 50) %>
              <%= current_user.email %> , 你好
            </a>

          <div class="navbar-dropdown">
            <%= link_to "新增文章", new_story_path, class: "navbar-item" %>
            <%= link_to "我的文章列表", stories_path, class: "navbar-item" %>
            <hr class="navbar-divider">

            <%= link_to "個人資料修改", edit_user_intro_path, class: "navbar-item" %>
            <%= link_to "密碼修改", edit_user_registration_path, class: "navbar-item" %>
            <hr class="navbar-divider">

            <%= link_to "登出", destroy_user_session_path, method: 'delete', class: "navbar-item", data: {confirm: "是否確定登出？"} %>

            <a class="navbar-item">
                Contact
            </a>
            <a class="navbar-item">
                Report an issue
            </a>
          </div>
          </div>
    
        <% else %>
          <% if controller_name != 'registrations' && controller_name != 'sessions' %>
            <%= link_to "註冊", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "登入", new_user_session_path, class: "button is-light" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>