config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/intro/edit', to: 'users/registrations#edit_intro', as: 'edit_user_intro'
    post 'users/intro/edit', to: 'users/registrations#update_intro', as: 'update_user_intro'
  end

  resources :user, only: [] do
    member do
      post :follow
    end
  end

  resources :stories do
    member do
      post :unpublish
      post :publish
      post :love
    end
    resources :comments, only: [:create]
  end

  get '@:username/:story_id', to: 'pages#show', as: 'story_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  
  resources :pending_stories


  root 'pages#index'


 

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/story.rb
require "babosa"

class Story < ApplicationRecord
  include AASM
  aasm column: 'status', no_direct_assignment: true do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  extend FriendlyId
  friendly_id :slug_options, use: :slugged

  
  # def destroy
  #   update(deleted_at: Time.now)
  # end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  
  ###
  acts_as_paranoid
  
  belongs_to :user
  has_one :pending_story, dependent: :destroy
  has_one_attached :cover_image
  has_many :comments

  validates :title, :content, presence: true

  # default_scope { where(deleted_at: nil )}
  scope :published_stories, -> {published.with_attached_cover_image.order(created_at: :desc).includes(:user)}

  
  private
  def slug_options
    [
      :title,
      [:title, SecureRandom.hex[0,8]]
    ]
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  before_action :authenticate_user!, except: [:love]
  before_action :find_story, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  skip_before_action :verify_authenticity_token, only: [:love]
  

  def index
    @stories = current_user.stories.order(updated_at: :desc)
  end

  def new
    @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)

    if @story.save
      if params[:publish]
        @story.publish!
        redirect_to stories_path, notice: '發布成功'
      else
        redirect_to edit_story_path(@story), notice: '儲存成功'
      end
    else
      render :new
    end
  end

  def show
  end 

  def edit
  end

  def update
    @pending_story = @story.build_pending_story(story_params)

    if @pending_story.save
      if params[:publish]
        @story.update(story_params)
        @story.publish! if @story.may_publish?
        redirect_to stories_path, notice: '發布成功'
        @pending_story.destroy
      else
        if @story.draft?
          @story.update(story_params) 
          redirect_to edit_story_path(@story), notice: '儲存成功'
          @pending_story.destroy
        else
          redirect_to edit_pending_story_path(@story), notice: '儲存成功'
        end
      end
    else
      render :edit
    end
  end

  def destroy
    if @story.pending_story != nil
      @story.pending_story.destroy 
    else
      @story.destroy
    end
    redirect_to stories_path, notice: '刪除成功！'
  end

  def publish
    if @story.pending_story != nil
      @story.cover_image.attach(@story.pending_story.cover_image.blob) if @story.pending_story.cover_image.attached?
      @story.update(title: @story.pending_story.title, content: @story.pending_story.content)
      @story.pending_story.destroy
      redirect_to stories_path, notice: '更新成功！'    
    else
      @story.publish!
      redirect_to stories_path, notice: '發布成功！'   
    end 
  end

  def unpublish
    @story.pending_story.destroy if @story.pending_story != nil
    @story.unpublish!
    redirect_to stories_path, notice: '下架成功，移至草稿區！'    
  end

  def love
    console.log('123')

    if user_signed_in?
      @story = Story.friendly.find(params[:id])
      @story.increment(:love)
      render json: {status: @story.love}
    else
      render json: {status: 'sign_in_first'}
    end
  end

  private
  def find_story
    @story = current_user.stories.friendly.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :content, :cover_image)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def cover_image(story, size: 250)
    image_tag story.cover_image.variant(resize_to_limit: [size, size]), class: 'cover-image' if story.cover_image.attached?
  end 
end

app/views/stories/_form.html.erb
<% if story.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% story.errors.full_messages.each do |message| %>
        <li>*<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<br>

<%= form_for(story) do |form| %>
  <div class="field">
    <div class="control">
      <%= image_tag story.cover_image.variant(resize_to_limit: [1000, 800]), class: 'cover-image' if story.cover_image.attached? %>
      <%= form.label :cover_image, '封面圖' %>
      <%= form.file_field :cover_image %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.label :title, '標題' %>
      <%= form.text_field :title, class: 'input is-primary' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.label :content, '內容' %>
      <%= form.text_area :content, rows: 10, class: 'textarea is-primary' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "儲存草稿", name: "save_as_draft", class: "button" %>
    <%- if story.status == 'draft' %>
      <%= form.submit "發布文章", name: "publish", class: "button is-primary" %>
    <% else %>
      <%= form.submit "更新文章", name: "publish", class: "button is-primary" %>
    <% end %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1 class='title'>編輯文章</h1>

<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<h1 class= 'title'>我的文章</h1>

<% @stories.each do |story| %>

  <div class="content">
    <div class="buttons">

      <h2 class="title">
        <%= link_to story.title, story_path(story), class: 'has-text-grey-darker' %>
        <%= content_tag :span, '已發佈', class: 'tag is-primary' if story.published? %>
        <%= content_tag :span, '未發佈', class: 'tag' if story.draft? %>
        <%= content_tag :span, '草稿編輯中', class: 'tag' if story.pending_story != nil %>
      </h2> 

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="is-hoverable navbar-link"></a>

        <div class="navbar-dropdown">
          <div>
            <% if story.pending_story != nil %>
              <%= link_to '繼續編輯草稿', edit_pending_story_path(story), class: "navbar-item" %>
              <%= link_to '以草稿更新文章', publish_story_path(story), method: 'post', class: "navbar-item" %>
              <%= link_to '刪除草稿', story_path(story), method: 'delete', class: "navbar-item", data:{confirm: '確認刪除？'} %>
            <% else %>
              <%= link_to '編輯文章', edit_story_path(story), class: "navbar-item" %>
            <% end %>
          </div>
          
          <%= link_to '發布文章', publish_story_path(story), method: 'post', class: "navbar-item" if story.draft? %>

          <div>
            <% if story.published? %>
              <%= link_to '下架文章', unpublish_story_path(story), method: 'post', class: "navbar-item", data:{confirm: '確認下架？'} %>
            <% else %>
              <%= link_to '刪除草稿', story_path(story), method: 'delete', class: "navbar-item", data:{confirm: '確認刪除？'} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <p><%= story.content %></p>

    <p>
      創建時間：<%= story.created_at.to_date %>，
      最後更新時間：<%= time_ago_in_words(story.updated_at) %>前
    </p>

    <% if story.pending_story != nil %>
      <%= link_to story.pending_story.title, pending_story_path(story), class: 'has-text-grey-darker' %>（草稿）
      <p><%= story.pending_story.content %></p>
    <% end %>

    <hr>
  </div>
<% end %> 

app/views/stories/new.html.erb
<h1 class= "title">新增文章</h1>

<%= render 'form', story: @story %>

app/views/stories/show.html.erb
<h1>當前文章</h1>

<div class="content">
    <div class="buttons">
      <h2 class="title">
        <%= @story.title %>
        <%= content_tag :span, '已發佈', class: 'tag is-primary' if @story.published? %>
        <%= content_tag :span, '未發佈', class: 'tag' if @story.draft? %>
        <%= content_tag :span, '草稿編輯中', class: 'tag' if @story.pending_story != nil %>
      </h2> 

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="is-hoverable navbar-link"></a>
        <div class="navbar-dropdown">
          <% if @story.pending_story != nil %>
            <%= link_to '編輯文章', edit_pending_story_path(@story), class: "navbar-item", data:{confirm: '已有正在編輯的草稿，是否繼續編輯？'} %>
          <% else %>
            <%= link_to '編輯文章', edit_story_path(@story), class: "navbar-item" %>
          <% end %>

          <div>
            <% if @story.published? %>
              <%= link_to '下架文章', unpublish_story_path(@story), method: 'post', class: "navbar-item", data:{confirm: '確認下架？'} %>
            <% else %>
              <%= link_to '刪除草稿', story_path(@story), method: 'delete', class: "navbar-item", data:{confirm: '確認刪除？'} %>
              <%= link_to '發布文章', publish_story_path(@story), method: 'post', class: "navbar-item" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <p><%= simple_format(@story.content).truncate(250) %></p>

    <p>
      創建時間：<%= @story.created_at.to_date %>，
      最後更新時間：<%= time_ago_in_words(@story.updated_at) %>前
    </p>
</div>